-- AlterTable
ALTER TABLE `recipes` MODIFY `uploadTime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `reviews` MODIFY `uploadTime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `users` MODIFY `uploadTime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
